#!/usr/bin/env php
<?php

// Configure these variables for your system:
$lando_full_path = '/usr/local/bin/lando';
$lando_sites_path_match = 'Sites/lando';

$options = [];
$arguments =[];

$arguments = array_filter($argv, function ($value) use (&$options) {
  if (substr($value, 0, 1) == '-') {
    $options[] = $value;
    return FALSE;
  }
  return TRUE;
});

// Discard path to this script.
array_shift($arguments);

$command = $lando_full_path . ' ' . implode(' ', $arguments) . ' ' . implode(' ', $options);

switch ($arguments[0]) {
  case "start":
  case "restart":
  case "build":
  case "rebuild":
  case "destroy":
  case "init":
    $alert = TRUE;
    break;
  default;
    $alert = FALSE;
    break;
}

// Execute the lando command
exec($command, $out, $exit_code_lando);
print implode("\n", $out);


// Optionally display a notification.
if ($alert) {

  // Determine success of command.
  if ($exit_code_lando == 0) {
    $lando_status = 'Success';
  }
  else {
    $lando_status = "Failed ($exit_code_lando)";
  }

  // Determine site on which we're operating.
  if (array_key_exists(1, $arguments)) {
    $site = $arguments[1];
  }
  else {
    preg_match("@$lando_sites_path_match/(\S+)@", $_SERVER['PWD'], $matches);
    if (is_array($matches) && array_key_exists(1, $matches)) {
      $site = 'Site: ' . $matches[1];
    }
    else {
      $site = '';
    }
  }

  // Display the MacOS notification
  $cmd_oascript = 'osascript -e "display notification \"' . $lando_status . '\" with title \"lando ' . $arguments[0] . '\" subtitle \"' . $site . '\" sound name \"Tink\""';
  exec($cmd_oascript, $out_oascript, $exit_code_oascript);

  if ($exit_code_oascript != 0) {
    print "Error: Failed to execute $cmd_oascript\n";
  }
}

exit($exit_code_lando);
